---
layout: post
title:  " Python Study (5)  "
date:   2018-02-08
excerpt: "  Python Study (5) "
cate : "post"
tag:
- Python
---

## 예외 처리

* 기본적인 try 구문의 사용법은 다음과 같다.

```
try:
    <예외 발생 가능성이 있는 문장>
except 예외 종류:
    <예외 처리 문장>
except ( 예외 1, 예외 2 ):
    <예외 처리 문장>
except 예외 as 인자:
    <예외 처리 문장>
else:
    <예외가 발생하지 않은 경우, 수행할 문장>
finally:
    <예외 발생 유무에 상관없이 try 블록 이후 수행할 문장>
```


{% highlight python %}

try:
    c = divide(5,"af")

except TypeError:
    print("모든 인자는 숫자여야 합니다.")

except TypeError as e:
    print("Error : ", e.args[0])        # 전달되는 예외 인스턴스 객체를 e로 받아서 사용

except ( ZeroDivisionError, OverflowError, FloatingPointError ): # 명시된 에러를 모두 처리
    print("수치 연산 관련 에러입니다. ")

else:
    print("Result : {0}" .format(c))

finally:
    print("항상 finally 블록은 수행됩니다.")

{% endhighlight %}

---

## raise 구문

* 사용자가 의도적으로 예외를 발생시켜야 하는 경우가 있다.

* 이러한 경우 `raise` 구문을 사용할 수 있다.

* `raise` 구문의 형식은 아래와 같다.

```
1. raise [Exception]            # 해당 예외를 발생시킨다.
2. raise [Exception(data)]      # 예외 발생 시 관련 데이터를 전달한다.
3. raise                        # 발생된 예외를 상위로 전달한다.
```

* 사용자 정의 예외를 생성하는 경우, 반드시 내장 클래스인 Exception을 상속바다 정의해야한다.

{% highlight python %}

def RaiseErrorFunc():
    raise NameError         # 내장 예외인 NameError를 발생

try:
    RaiseErrorFunc()

except :
    print("NameErro is Catched.")


NameErro is Catched.

{% endhighlight %}

---

* 예외를 상위로 전달(Propagation)하는 예제이다.


{% highlight python %}
def RaiseErrorFunc():
    raise NameError("NameError의 인자")
def PropagateError():
    try:
        RaiseErrorFunc()
    except :
        print("에러 전달 이전에 먼저 이 메시지가 출력됩니다.")
        raise           # 발생한 에러를 상위로 전달


PropagateError()





에러 전달 이전에 먼저 이 메시지가 출력됩니다.
Traceback (most recent call last):
  File "/Users/gy8971/Desktop/gid/1.Programming/Python/init.py", line 11, in <module>
    PropagateError()
  File "/Users/gy8971/Desktop/gid/1.Programming/Python/init.py", line 5, in PropagateError
    RaiseErrorFunc()
  File "/Users/gy8971/Desktop/gid/1.Programming/Python/init.py", line 2, in RaiseErrorFunc
    raise NameError("NameError의 인자")
NameError: NameError의 인자

{% endhighlight %}

* RaiseErrorFunc() 함수에 의해 NameError 에러가 발생하며, <br> 처리하는 부분이 없기 때문에 발생한 에러는 PropagateError() 함수로 전달된다.

* 예외를 받은 PropagateError() 함수에서는 화면에 메시지를 출력하고 받은 예외를 그대로 상위로 전달한다.

* 전달된 예외는 처리하는 부분이 없기 때문에 출력 결과에서 확인할 수 있듯이 프롬포트에 에러를 출력한다.

* 출력 결과에서 예외가 발생할 때의 `콜 스택` 정보와 raise 구문에서 전달한 인자를 확인할 수 있다.

---

## 사용자정의 예외

* 내장 예외만으로 표현하는 데 한계가 있다.

* 사용자정의 예외에 대해 알아보자.

{% highlight python %}

class NegativeDivisionError(Exception):
    def __init__(self, value):
        self.value = value

def PositiveDivide(a,b):
    if( b < 0 ):
        raise NegativeDivisionError(b)
    return a / b
        

try:
    ret = PositiveDivide(10,-3)
except NegativeDivisionError as e:
    print('Negative Error :', e.value)
except ZeroDivisionError as e:
    print('Zero Error :', e.args[0])
except :
    print('Unexpected Exception!')


# b = -3일 때    
Negative Error : -3               

# b = 0일 때    
Zero Error : division by zero

{% endhighlight %}

* 모든 사용자정의 예외는 내장 예외인 Exception 클래스나 그 하위 클래스를 상속받아 구현해야 한다.

* 전달해야 할 인자가 있는 경우에는 생성자에서 클래스 멤버 변수를 이용해 저장할 수 있다.

* 이렇게 정의된 클래스는 개발자가 원하는 경우에 raise 구문으로 예외를 발생시킬 수 있다.

---

## assert 구문

* 일반적으로 `assert` 구문은 개발 과정에서 `제약사항`을 `설정`할 `목적`으로 사용하며, <br> 인자로 받은 조건식이 거짓인 경우 `AssertionError`가 발생한다.

```
assert <조건식>, <관련 데이터>
```

위의 표현식은 다음과 동일하다.


{% highlight python %}
if __debug__:
    if not <조건식>:
        raise AssertionError(<관련 데이터>)
{% endhighlight %}

* <관련 데이터>는 예외가 발생할 경우에 `AssertionError`의 인자로 전달되며 생략 가능하다.

* 내부 변수인 `__debug__`가 True인 경우에만 `assert` 구문이 활성화되며, False인 경우에는 수행되지 않는다.


{% highlight python %}

def foo(x):
    assert type(x) == int, "Input value must be integer"
    return x * 10

ret = foo("A")
print(ret)



Traceback (most recent call last):
  File "/Users/gy8971/Desktop/gid/1.Programming/Python/init.py", line 6, in <module>
    ret = foo("A")
  File "/Users/gy8971/Desktop/gid/1.Programming/Python/init.py", line 3, in foo
    assert type(x) == int, "Input value must be integer"
AssertionError: Input value must be integer

{% endhighlight %}